In [107]:
import numpy as np
import statistics

In [108]:
class KNN_classifier():
    
    def __init__(self,distance_metric):
        self.distance_metric=distance_metric
        
        
    def get_distance_metric(self,p1,p2):
        if(self.distance_metric=='eucledian'):
            dist=0
            for i in range(len(p1)-1):
                dist+=(p1[i]-p2[i])**2
            
            eucledian_dist=np.sqrt(dist)
            return eucledian_dist
        elif(self.distance_metric=='manhattan'):
            dist=0
            for i in range(len(p1)-1):
                dist+=abs(p1[i]-p2[i])
            manhattan_dist=dist
            return manhattan_dist
            
            
    
    def nearest_ngh(self,X_train,test_data,k):
        distance_metric=[]
        for training_data in X_train: 
            distance=self.get_distance_metric(training_data,test_data)
            distance_metric.append([training_data,distance])
            
        distance_metric.sort(key=lambda x:x[1])
        
        
        neighbour_list=[]
        for i in range(k):
            neighbour_list.append(distance_metric[i][0])
            
        return neighbour_list
            
    
    
    def predict(self,X_train,test_data,k):
        neighbours=self.nearest_ngh(X_train,test_data,k)
        label=[]
        for data in neighbours:
            label.append(data[-1])
            
        predicted_class=statistics.mode(label)
        return predicted_class

Prediction from a Dataset

In [109]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [110]:
df=pd.read_csv('diabetes.csv')

In [111]:
df.head()

   Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [112]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [113]:
df.describe()

       Pregnancies     Glucose  ...         Age     Outcome
count   768.000000  768.000000  ...  768.000000  768.000000
mean      3.845052  120.894531  ...   33.240885    0.348958
std       3.369578   31.972618  ...   11.760232    0.476951
min       0.000000    0.000000  ...   21.000000    0.000000
25%       1.000000   99.000000  ...   24.000000    0.000000
50%       3.000000  117.000000  ...   29.000000    0.000000
75%       6.000000  140.250000  ...   41.000000    1.000000
max      17.000000  199.000000  ...   81.000000    1.000000

[8 rows x 9 columns]

In [114]:
X=df.drop(['Outcome'],axis=1)
y=df['Outcome']

X=X.to_numpy()
y=y.to_numpy()

In [115]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,stratify=y,random_state=2)

In [116]:
X_train.shape

(614, 8)

In [117]:
X_train=np.insert(X_train,8,y_train,axis=1)

X_train->traning data with output


x_test->test data without output

In [118]:
classifier=KNN_classifier(distance_metric='eucledian')

In [119]:
# Our class can only predict for one point at a time

prediction=classifier.predict(X_train,X_test[0],k=5)

In [120]:
print(prediction)

0.0

In [121]:
print(y_test[0])

0

In [122]:
# prediction for multiple points

y_pred=[]
for i in range(X_test.shape[0]):
    prediction=classifier.predict(X_train,X_test[i],k=5)
    y_pred.append(prediction)

In [127]:
accuracy_score(y_test,y_pred)*100

72.72727272727273